import { useEffect, useState } from "react";
import { useLayout } from "../../hooks/useLayout.jsx";

const ContactPage = () => {
    const { setHeadline, setActions } = useLayout();

    useEffect(() => {
        setHeadline("Kontakte");
        setActions(
        );

        return () => {
            setHeadline("");
            setActions(null);
        };
    }, []);

    return (
        <>
            <h2>Kontakte</h2>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab aliquam architecto asperiores cumque debitis eaque explicabo facilis harum ipsum natus nemo, obcaecati qui sapiente tenetur voluptates. At consequuntur fugiat neque!</span><span>Aliquam commodi dicta exercitationem hic illum, nemo quos reprehenderit voluptas voluptatem. Aspernatur debitis ducimus exercitationem iure modi nesciunt odit quas sapiente. Aliquam exercitationem incidunt magnam modi possimus quibusdam ut, velit.</span><span>Animi delectus deserunt eius et, iste laudantium magnam nobis praesentium. At atque culpa cumque deserunt dicta ducimus hic impedit iste magnam molestias necessitatibus, officiis quibusdam recusandae totam ullam vitae voluptatibus?</span><span>Assumenda cum, esse est fugit in modi, nisi obcaecati quas repellendus suscipit, velit veniam voluptate voluptatem! Beatae, cum, cumque deserunt distinctio, fuga maiores modi molestias quaerat sed similique ut vitae?</span><span>A ad aperiam eligendi, est facere fugiat ipsa itaque iure laborum laudantium magni omnis pariatur placeat quibusdam quo reiciendis sequi similique, velit? Culpa fugit nam nemo qui quis, sapiente tempora?</span><span>A aperiam consequuntur corporis ipsam maiores porro, veniam voluptates voluptatum? Culpa ex hic nam! Dolore illo impedit nobis quae! Accusantium aspernatur autem dolorem esse, ex itaque iusto maiores quas quis?</span><span>Consectetur debitis, laborum nobis omnis quibusdam ratione ullam. Ab aliquam at commodi dignissimos illum itaque laborum molestias officia officiis quaerat, quasi, quidem ratione repellendus ullam, voluptas. Incidunt molestias perspiciatis vel.</span><span>Accusamus accusantium asperiores at doloremque dolores eaque, harum incidunt mollitia nisi nulla placeat quasi quia, quisquam! Adipisci aspernatur autem eaque inventore minima nulla, optio pariatur provident quod rem temporibus voluptas.</span><span>Cumque, facilis fugit illo nisi quos voluptatum. A autem earum et eum incidunt, modi nesciunt sed. Blanditiis harum, hic ipsam minima nisi provident quasi quidem soluta totam velit? Architecto, reiciendis!</span><span>At aut est laboriosam nesciunt ratione recusandae veniam! Enim eveniet facere ipsam maiores repellat totam ut? Ab ad, distinctio ducimus ex fugiat id incidunt numquam optio placeat quaerat quisquam velit.</span></p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab aliquam architecto asperiores cumque debitis eaque explicabo facilis harum ipsum natus nemo, obcaecati qui sapiente tenetur voluptates. At consequuntur fugiat neque!</span><span>Aliquam commodi dicta exercitationem hic illum, nemo quos reprehenderit voluptas voluptatem. Aspernatur debitis ducimus exercitationem iure modi nesciunt odit quas sapiente. Aliquam exercitationem incidunt magnam modi possimus quibusdam ut, velit.</span><span>Animi delectus deserunt eius et, iste laudantium magnam nobis praesentium. At atque culpa cumque deserunt dicta ducimus hic impedit iste magnam molestias necessitatibus, officiis quibusdam recusandae totam ullam vitae voluptatibus?</span><span>Assumenda cum, esse est fugit in modi, nisi obcaecati quas repellendus suscipit, velit veniam voluptate voluptatem! Beatae, cum, cumque deserunt distinctio, fuga maiores modi molestias quaerat sed similique ut vitae?</span><span>A ad aperiam eligendi, est facere fugiat ipsa itaque iure laborum laudantium magni omnis pariatur placeat quibusdam quo reiciendis sequi similique, velit? Culpa fugit nam nemo qui quis, sapiente tempora?</span><span>A aperiam consequuntur corporis ipsam maiores porro, veniam voluptates voluptatum? Culpa ex hic nam! Dolore illo impedit nobis quae! Accusantium aspernatur autem dolorem esse, ex itaque iusto maiores quas quis?</span><span>Consectetur debitis, laborum nobis omnis quibusdam ratione ullam. Ab aliquam at commodi dignissimos illum itaque laborum molestias officia officiis quaerat, quasi, quidem ratione repellendus ullam, voluptas. Incidunt molestias perspiciatis vel.</span><span>Accusamus accusantium asperiores at doloremque dolores eaque, harum incidunt mollitia nisi nulla placeat quasi quia, quisquam! Adipisci aspernatur autem eaque inventore minima nulla, optio pariatur provident quod rem temporibus voluptas.</span><span>Cumque, facilis fugit illo nisi quos voluptatum. A autem earum et eum incidunt, modi nesciunt sed. Blanditiis harum, hic ipsam minima nisi provident quasi quidem soluta totam velit? Architecto, reiciendis!</span><span>At aut est laboriosam nesciunt ratione recusandae veniam! Enim eveniet facere ipsam maiores repellat totam ut? Ab ad, distinctio ducimus ex fugiat id incidunt numquam optio placeat quaerat quisquam velit.</span></p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab aliquam architecto asperiores cumque debitis eaque explicabo facilis harum ipsum natus nemo, obcaecati qui sapiente tenetur voluptates. At consequuntur fugiat neque!</span><span>Aliquam commodi dicta exercitationem hic illum, nemo quos reprehenderit voluptas voluptatem. Aspernatur debitis ducimus exercitationem iure modi nesciunt odit quas sapiente. Aliquam exercitationem incidunt magnam modi possimus quibusdam ut, velit.</span><span>Animi delectus deserunt eius et, iste laudantium magnam nobis praesentium. At atque culpa cumque deserunt dicta ducimus hic impedit iste magnam molestias necessitatibus, officiis quibusdam recusandae totam ullam vitae voluptatibus?</span><span>Assumenda cum, esse est fugit in modi, nisi obcaecati quas repellendus suscipit, velit veniam voluptate voluptatem! Beatae, cum, cumque deserunt distinctio, fuga maiores modi molestias quaerat sed similique ut vitae?</span><span>A ad aperiam eligendi, est facere fugiat ipsa itaque iure laborum laudantium magni omnis pariatur placeat quibusdam quo reiciendis sequi similique, velit? Culpa fugit nam nemo qui quis, sapiente tempora?</span><span>A aperiam consequuntur corporis ipsam maiores porro, veniam voluptates voluptatum? Culpa ex hic nam! Dolore illo impedit nobis quae! Accusantium aspernatur autem dolorem esse, ex itaque iusto maiores quas quis?</span><span>Consectetur debitis, laborum nobis omnis quibusdam ratione ullam. Ab aliquam at commodi dignissimos illum itaque laborum molestias officia officiis quaerat, quasi, quidem ratione repellendus ullam, voluptas. Incidunt molestias perspiciatis vel.</span><span>Accusamus accusantium asperiores at doloremque dolores eaque, harum incidunt mollitia nisi nulla placeat quasi quia, quisquam! Adipisci aspernatur autem eaque inventore minima nulla, optio pariatur provident quod rem temporibus voluptas.</span><span>Cumque, facilis fugit illo nisi quos voluptatum. A autem earum et eum incidunt, modi nesciunt sed. Blanditiis harum, hic ipsam minima nisi provident quasi quidem soluta totam velit? Architecto, reiciendis!</span><span>At aut est laboriosam nesciunt ratione recusandae veniam! Enim eveniet facere ipsam maiores repellat totam ut? Ab ad, distinctio ducimus ex fugiat id incidunt numquam optio placeat quaerat quisquam velit.</span></p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab aliquam architecto asperiores cumque debitis eaque explicabo facilis harum ipsum natus nemo, obcaecati qui sapiente tenetur voluptates. At consequuntur fugiat neque!</span><span>Aliquam commodi dicta exercitationem hic illum, nemo quos reprehenderit voluptas voluptatem. Aspernatur debitis ducimus exercitationem iure modi nesciunt odit quas sapiente. Aliquam exercitationem incidunt magnam modi possimus quibusdam ut, velit.</span><span>Animi delectus deserunt eius et, iste laudantium magnam nobis praesentium. At atque culpa cumque deserunt dicta ducimus hic impedit iste magnam molestias necessitatibus, officiis quibusdam recusandae totam ullam vitae voluptatibus?</span><span>Assumenda cum, esse est fugit in modi, nisi obcaecati quas repellendus suscipit, velit veniam voluptate voluptatem! Beatae, cum, cumque deserunt distinctio, fuga maiores modi molestias quaerat sed similique ut vitae?</span><span>A ad aperiam eligendi, est facere fugiat ipsa itaque iure laborum laudantium magni omnis pariatur placeat quibusdam quo reiciendis sequi similique, velit? Culpa fugit nam nemo qui quis, sapiente tempora?</span><span>A aperiam consequuntur corporis ipsam maiores porro, veniam voluptates voluptatum? Culpa ex hic nam! Dolore illo impedit nobis quae! Accusantium aspernatur autem dolorem esse, ex itaque iusto maiores quas quis?</span><span>Consectetur debitis, laborum nobis omnis quibusdam ratione ullam. Ab aliquam at commodi dignissimos illum itaque laborum molestias officia officiis quaerat, quasi, quidem ratione repellendus ullam, voluptas. Incidunt molestias perspiciatis vel.</span><span>Accusamus accusantium asperiores at doloremque dolores eaque, harum incidunt mollitia nisi nulla placeat quasi quia, quisquam! Adipisci aspernatur autem eaque inventore minima nulla, optio pariatur provident quod rem temporibus voluptas.</span><span>Cumque, facilis fugit illo nisi quos voluptatum. A autem earum et eum incidunt, modi nesciunt sed. Blanditiis harum, hic ipsam minima nisi provident quasi quidem soluta totam velit? Architecto, reiciendis!</span><span>At aut est laboriosam nesciunt ratione recusandae veniam! Enim eveniet facere ipsam maiores repellat totam ut? Ab ad, distinctio ducimus ex fugiat id incidunt numquam optio placeat quaerat quisquam velit.</span></p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab aliquam architecto asperiores cumque debitis eaque explicabo facilis harum ipsum natus nemo, obcaecati qui sapiente tenetur voluptates. At consequuntur fugiat neque!</span><span>Aliquam commodi dicta exercitationem hic illum, nemo quos reprehenderit voluptas voluptatem. Aspernatur debitis ducimus exercitationem iure modi nesciunt odit quas sapiente. Aliquam exercitationem incidunt magnam modi possimus quibusdam ut, velit.</span><span>Animi delectus deserunt eius et, iste laudantium magnam nobis praesentium. At atque culpa cumque deserunt dicta ducimus hic impedit iste magnam molestias necessitatibus, officiis quibusdam recusandae totam ullam vitae voluptatibus?</span><span>Assumenda cum, esse est fugit in modi, nisi obcaecati quas repellendus suscipit, velit veniam voluptate voluptatem! Beatae, cum, cumque deserunt distinctio, fuga maiores modi molestias quaerat sed similique ut vitae?</span><span>A ad aperiam eligendi, est facere fugiat ipsa itaque iure laborum laudantium magni omnis pariatur placeat quibusdam quo reiciendis sequi similique, velit? Culpa fugit nam nemo qui quis, sapiente tempora?</span><span>A aperiam consequuntur corporis ipsam maiores porro, veniam voluptates voluptatum? Culpa ex hic nam! Dolore illo impedit nobis quae! Accusantium aspernatur autem dolorem esse, ex itaque iusto maiores quas quis?</span><span>Consectetur debitis, laborum nobis omnis quibusdam ratione ullam. Ab aliquam at commodi dignissimos illum itaque laborum molestias officia officiis quaerat, quasi, quidem ratione repellendus ullam, voluptas. Incidunt molestias perspiciatis vel.</span><span>Accusamus accusantium asperiores at doloremque dolores eaque, harum incidunt mollitia nisi nulla placeat quasi quia, quisquam! Adipisci aspernatur autem eaque inventore minima nulla, optio pariatur provident quod rem temporibus voluptas.</span><span>Cumque, facilis fugit illo nisi quos voluptatum. A autem earum et eum incidunt, modi nesciunt sed. Blanditiis harum, hic ipsam minima nisi provident quasi quidem soluta totam velit? Architecto, reiciendis!</span><span>At aut est laboriosam nesciunt ratione recusandae veniam! Enim eveniet facere ipsam maiores repellat totam ut? Ab ad, distinctio ducimus ex fugiat id incidunt numquam optio placeat quaerat quisquam velit.</span></p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab aliquam architecto asperiores cumque debitis eaque explicabo facilis harum ipsum natus nemo, obcaecati qui sapiente tenetur voluptates. At consequuntur fugiat neque!</span><span>Aliquam commodi dicta exercitationem hic illum, nemo quos reprehenderit voluptas voluptatem. Aspernatur debitis ducimus exercitationem iure modi nesciunt odit quas sapiente. Aliquam exercitationem incidunt magnam modi possimus quibusdam ut, velit.</span><span>Animi delectus deserunt eius et, iste laudantium magnam nobis praesentium. At atque culpa cumque deserunt dicta ducimus hic impedit iste magnam molestias necessitatibus, officiis quibusdam recusandae totam ullam vitae voluptatibus?</span><span>Assumenda cum, esse est fugit in modi, nisi obcaecati quas repellendus suscipit, velit veniam voluptate voluptatem! Beatae, cum, cumque deserunt distinctio, fuga maiores modi molestias quaerat sed similique ut vitae?</span><span>A ad aperiam eligendi, est facere fugiat ipsa itaque iure laborum laudantium magni omnis pariatur placeat quibusdam quo reiciendis sequi similique, velit? Culpa fugit nam nemo qui quis, sapiente tempora?</span><span>A aperiam consequuntur corporis ipsam maiores porro, veniam voluptates voluptatum? Culpa ex hic nam! Dolore illo impedit nobis quae! Accusantium aspernatur autem dolorem esse, ex itaque iusto maiores quas quis?</span><span>Consectetur debitis, laborum nobis omnis quibusdam ratione ullam. Ab aliquam at commodi dignissimos illum itaque laborum molestias officia officiis quaerat, quasi, quidem ratione repellendus ullam, voluptas. Incidunt molestias perspiciatis vel.</span><span>Accusamus accusantium asperiores at doloremque dolores eaque, harum incidunt mollitia nisi nulla placeat quasi quia, quisquam! Adipisci aspernatur autem eaque inventore minima nulla, optio pariatur provident quod rem temporibus voluptas.</span><span>Cumque, facilis fugit illo nisi quos voluptatum. A autem earum et eum incidunt, modi nesciunt sed. Blanditiis harum, hic ipsam minima nisi provident quasi quidem soluta totam velit? Architecto, reiciendis!</span><span>At aut est laboriosam nesciunt ratione recusandae veniam! Enim eveniet facere ipsam maiores repellat totam ut? Ab ad, distinctio ducimus ex fugiat id incidunt numquam optio placeat quaerat quisquam velit.</span></p>
        </>
    )
}
    );
};

export default ContactPage;
